x=min(4,5,1)
y=max(5.3,2.0,5.4)
a=int(input("enter an integer:"))
z=abs(a)
b=pow(2,4)
print(x)
print(y)
print(z)
print(b)
import math
c=math.sqrt(256)
r=float(input("enter a number"))
s=math.ceil(r)
t=math.floor(r)
print(s)
print(t)
